algoritmo "semnome"
// Função :
// Autor :
// Data : 28/10/2023
// Seção de Declarações 
var
A: inteiro
B: real
inicio
// Seção de Comandos 
A <- abs(-50) // Absoluto
escreval("Absoluto: ", A)
B <- exp(9,5)   // Exponencial
escreval("Exponencial: ", B)
B <- raizq(81)
escreval("Raiz Quadrada: ", B)
B <- int(raizq(91))
escreval("Apenas o Inteiro da Raiz Quadrada: ", B)
B <- graupRad(90)
escreval("Graus radianos: ", B)
B <- sen(graupRad(90))
escreva("O seno: ", B)
fimalgoritmo
